export const transactions =  [
        {
          id: '1',
          transactionDate: '05.01.2023',
          type: "INCOME",
          category: 'food',
          userID: '111',
          comment: 'comment',
          amount: 30,
          balanceAfter: 0,
        },
        {
          id: '2',
          transactionDate: '19.01.2023',
          type: "EXPENCE",
          category: 'food',
          userID: '222',
          comment: 'comment',
          amount: 10,
          balanceAfter: 0,
        },
        {
          id: '3',
          transactionDate: '20.01.2023',
          type: "EXPENCE",
          category: 'food',
          userID: '333',
          comment: 'comment',
          amount: 40,
          balanceAfter: 0,
        },
        {
          id: '4',
          transactionDate: '20.01.2023',
          type: "EXPENCE",
          category: 'clother',
          userID: '333',
          comment: 'comment',
          amount: 60,
          balanceAfter: 0,
        },
        {
          id: '5',
          transactionDate: '20.01.2023',
          type: "EXPENCE",
          category: 'clother',
          userID: '333',
          comment: 'comment',
          amount: 60,
          balanceAfter: 0,
        },
        {
          id: '6',
          transactionDate: '20.01.2023',
          type: "EXPENCE",
          category: 'clother',
          userID: '333',
          comment: 'comment',
          amount: 60,
          balanceAfter: 0,
        },
      ];
